# Generated by Django 5.2.4 on 2025-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateTimeField(verbose_name='Appointment Date')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Patient Name')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='Doctor Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointment',
                'ordering': ['appointment_date'],
            },
        ),
    ]
