# Generated by Django 5.2.4 on 2025-08-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availability',
            table='Availability',
        ),
    ]
